spring:
  application:
    name: flowcare-backend
  profiles:
    active: dev
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

seed:
  enabled: ${SEED_ENABLED:true}
  file-path: classpath:data/seed.json
